site_name: R Development Environment Docs
site_url: https://example.com/
theme: readthedocs
nav:
    - 'Home': index.md
    - 'Tutorials':
        - 'Starting Codespace' : 'tutorials/creating_codespace.md'
        - 'Running R' : 'tutorials/running_r.md'
        - 'Building R': 'tutorials/building_r.md'
        - 'R Contribution Workflow' : 'tutorials/contribution_workflow.md'
        - 'Local Setup' : 'tutorials/localsetup.md'
        - 'Restarting and Stopping' : 'tutorials/codespacestartstop.md'
    - 'Resources' : resources.md